name: deploy on push

on:
  push:

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: List files before deployment (Debugging)
        run: ls -lR ./html/

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "html/**"  
          target: "/var/www/html"
          strip_components: 1
          debug: true  
